INSERT INTO users (
    username,
    email,
    password,
    display_name,
    current_status,
    created_at,
    updated_at
) VALUES
(
    'alex',
    'alex@test.com',
    '$2a$10$fakehashedpasswordalex',
    'Alex',
    'online',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'marie',
    'marie@test.com',
    '$2a$10$fakehashedpasswordmarie',
    'Marie',
    'offline',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'thomas',
    'thomas@test.com',
    '$2a$10$fakehashedpasswordthomas',
    'Thomas',
    'absent',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'lucie',
    'lucie@test.com',
    '$2a$10$fakehashedpasswordlucie',
    'Lucie',
    'online',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'kevin',
    'kevin@test.com',
    '$2a$10$fakehashedpasswordkevin',
    'Kevin',
    'offline',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
