# Base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/fourth_argument
spring.datasource.username=alexandre
spring.datasource.password=260701

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Port du serveur
server.port=8081

# JWT (HS256: secret >= 32 caractères)
jwt.secret=${JWT_SECRET:thisIsMySecretKeyForErisJwtAuthMustBe32CharsMin}
jwt.expiration=3600000